/*
 * JPanelRegistroMedicion.java
 *
 * Created on 18 de noviembre de 2007, 18:25
 */

package layout.panels;

import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import scr.dao.ProductorDao;
import scr.dao.RegistroMedicionDao;
import scr.dao.SectoresDao;
import scr.dao.SensoresDao;
import scr.entidades.Productor;
import scr.entidades.Sector;
import scr.entidades.Sensor;


import layout.utils.DateUtil;

/**
 *
 * @author  Administrador
 */
public class JPanelAltaRegistroMedicion extends javax.swing.JPanel {
        
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form JPanelRegistroMedicion */
    public JPanelAltaRegistroMedicion() {
        initComponents();
        extraInitComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProductor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSector = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSensor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonRegistrarMedicion = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo1.setDateFormat(DateUtil.formatDate);
        dateChooserCombo1.setVisible(false);
        jLabelErrorProductor = new javax.swing.JLabel();
        jLabelErrorSector = new javax.swing.JLabel();
        jLabelErrorSensor = new javax.swing.JLabel();
        jLabelErrorValorMedicion = new javax.swing.JLabel();

        jLabel1.setText("Registrar Medici\u00f3n");

        jLabel2.setText("Productor");

        jComboBoxProductor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<     >"}));
        jComboBoxProductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProductorActionPerformed(evt);
            }
        });
        jLabel3.setText("Sector");

        jComboBoxSector.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "<     >" }));
        jComboBoxSector.setEnabled(false);
        jComboBoxSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSectorActionPerformed(evt);
            }
        });

        jLabel4.setText("Sensor");

        jComboBoxSensor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<   >"}));
        jComboBoxSensor.setEnabled(false);

        jLabel5.setText("Valor Medici\u00f3n");

        jLabel6.setText("Fecha Registraci\u00f3n");
        jLabel6.setVisible(false);

        jButtonRegistrarMedicion.setText("Registrar");
        jButtonRegistrarMedicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarMedicionActionPerformed(evt);
            }
        });

        jLabelErrorProductor.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorProductor.setText("jLabel7");

        jLabelErrorSector.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorSector.setText("jLabel8");

        jLabelErrorSensor.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorSensor.setText("jLabel9");

        jLabelErrorValorMedicion.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorValorMedicion.setText("jLabel10");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6))
                        .add(49, 49, 49)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dateChooserCombo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButtonRegistrarMedicion)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jComboBoxProductor, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jComboBoxSector, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jComboBoxSensor, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jTextField1))
                                .add(48, 48, 48)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabelErrorValorMedicion)
                                    .add(jLabelErrorSensor)
                                    .add(jLabelErrorSector)
                                    .add(jLabelErrorProductor))))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jComboBoxProductor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabelErrorProductor)))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jComboBoxSector, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabelErrorSector)))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jComboBoxSensor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabelErrorSensor)))
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabelErrorValorMedicion)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dateChooserCombo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(13, 13, 13)
                .add(jButtonRegistrarMedicion)
                .add(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSectorActionPerformed
    	
        loadComboSector();
    }//GEN-LAST:event_jComboBoxSectorActionPerformed

    private void jComboBoxSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSectorActionPerformed
        loadComboSensor();
    }//GEN-LAST:event_jComboBoxSectorActionPerformed

    private void jButtonRegistrarMedicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarMedicionActionPerformed
        
        boolean validateOk = validarAltaMedicion();
        if(validateOk) {
          RegistroMedicionDao dao = new RegistroMedicionDao(); 
          int idSensor = ((Sensor)jComboBoxSensor.getSelectedItem()).getIdSensor();
          Float valor = new Float(Float.parseFloat(jTextField1.getText()));
          try {
        	  Integer devolucion = dao.insertRegistroMedicion(idSensor,valor);
        	  jComboBoxProductor.setEnabled(false);
        	  jComboBoxSector.setEnabled(false);
        	  jComboBoxSensor.setEnabled(false);
        	  jTextField1.setEnabled(false);
        	  if (devolucion.intValue() != 0)       	  
        		  JOptionPane.showMessageDialog(new JFrame(), "Registro Medicion cargado correctamente", "Dialog",
        				  JOptionPane.INFORMATION_MESSAGE);
        	  else
        		  JOptionPane.showMessageDialog(new JFrame(), "Error. ", "Dialog",
      	    	        JOptionPane.ERROR_MESSAGE);
          }catch(Exception e) {
        	  JOptionPane.showMessageDialog(new JFrame(), "Error. " + e  , "Dialog",
    	    	        JOptionPane.ERROR_MESSAGE);
          }
        } 
    }//GEN-LAST:event_jButtonRegistrarMedicionActionPerformed

    private void extraInitComponents() {
        loadCombos();
        initLabelsError();
    }

     private void initLabelsError() {
        jLabelErrorProductor.setVisible(false);
        jLabelErrorSector.setVisible(false);
        jLabelErrorSensor.setVisible(false);
        jLabelErrorValorMedicion.setVisible(false);
    }
    
    private void loadCombos() {
        loadComboProductor();

    }

    private void loadComboSensor() {
    	if(jComboBoxSector.getItemCount() > 0) {
    		int idSector = ((Sector)jComboBoxSector.getSelectedItem()).getIdsector();
    		SensoresDao dao = new SensoresDao();
    		jComboBoxSensor.removeAllItems();
        	this.loadComboSen(dao.getSensores(idSector));
        	jComboBoxSensor.setEnabled(true);
    	} 
    }
    private void loadComboSen(Vector<Sensor> sensores) {
		 for (Sensor s : sensores) {
			 jComboBoxSensor.addItem(s);
     }
	}
    private void loadComboSector() {
    	int idProductor = ((Productor)jComboBoxProductor.getSelectedItem()).getIdProductor();
    	SectoresDao dao = new SectoresDao();
//    	for(int i = 1; i < jComboBoxSector.getItemCount(); i++) {
//    		jComboBoxSector.removeItemAt(i);
//    	}
    	jComboBoxSector.removeAllItems();
    	//jComboBoxSector.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  "<     >" }));
    	this.loadComboSec(dao.getSectoresByProductor(idProductor));
    	jComboBoxSector.setEnabled(true);
    }
    private void loadComboSec(Vector<Sector> sectores) {
		 for (Sector s : sectores) {
			 jComboBoxSector.addItem(s);
      }
	}

    private void loadComboProductor() {
    	ProductorDao dao = new ProductorDao();
    	this.loadComboProd(dao.getProductores());
    }
    private void loadComboProd(Vector<Productor> productores) {
		 for (Productor p : productores) {
			 jComboBoxProductor.addItem(p);
       }
	}
    
    private boolean validarAltaMedicion() {
//        boolean validate = validateProductor() && validateSector() && 
//                            validateSensor() && validarMedicion();
//        return validate;
        return true;
    }

    private boolean validateSensor() {
        boolean validate = validateCombo(jComboBoxSensor);
        if(!validate) {
           putError(jLabelErrorSensor, "Debe seleccionar un Sensor");
        } else {
            jLabelErrorSensor.setVisible(false);
        }
        return validate;
    }

    private boolean validarMedicion() {
    	try {
    	Float valor = new Float(Float.parseFloat(jTextField1.getText()));
    	if (valor.floatValue() > -20 && valor.floatValue() < 70)
    		return true;
    	else
    		return false;
    	}catch(Exception e){
    		return false;
    	}
    }

    private boolean validateProductor() {
         boolean validate = validateCombo(jComboBoxProductor);
        if(!validate) {
           putError(jLabelErrorProductor, "Debe seleccionar un Productor");
        } else {
            jLabelErrorProductor.setVisible(false);
        }
        return validate;
    }

    private boolean validateSector() {
        boolean validate = validateCombo(jComboBoxSector);
        if(!validate) {
           putError(jLabelErrorSector, "Debe seleccionar un Sector");
        } else {
            jLabelErrorSector.setVisible(false);
        }
        return validate;
    }
    
     private void putError(JLabel labelError, String messageError) {
        labelError.setText(messageError);
        labelError.setVisible(true);
    }

    private boolean validateCombo(JComboBox jComboBox) {
        int indexSelected = jComboBox.getSelectedIndex();
        return indexSelected > 0;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButtonRegistrarMedicion;
    private javax.swing.JComboBox jComboBoxProductor;
    private javax.swing.JComboBox jComboBoxSector;
    private javax.swing.JComboBox jComboBoxSensor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelErrorProductor;
    private javax.swing.JLabel jLabelErrorSector;
    private javax.swing.JLabel jLabelErrorSensor;
    private javax.swing.JLabel jLabelErrorValorMedicion;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
