package layout.panels;

import java.awt.Component;
import java.awt.Dimension;
import java.sql.Time;
import java.text.ParseException;
import java.util.Date;

import layout.utils.DateUtil;
import scr.dao.CampoDao;
import scr.dao.ContratoDao;
import scr.dao.SectoresDao;
import scr.dao.TipoCultivoDao;
import scr.entidades.Campo;
import scr.entidades.Contrato;
import scr.entidades.Sector;
import scr.entidades.TipoCultivo;

/**
 *
 * @author  ZIGGY STARDUST
 */
public class JPanelAltaSector extends javax.swing.JPanel {
    
	private static final long serialVersionUID = 6119223212634441001L;

	private SectoresDao sectorDao = new SectoresDao();
	private CampoDao campoDao = new CampoDao();
	private TipoCultivoDao tipoCultivoDao = new TipoCultivoDao();
	private ContratoDao contratoDao = new ContratoDao();
	
	/** Creates new form JPanelAltaSector */
    public JPanelAltaSector() {
        initComponents();
        extraInitComponents();
    }
    
    private void extraInitComponents() {
    	dCCFechaIni.setDateFormat(DateUtil.formatDate);
        dCCFechaFin.setDateFormat(DateUtil.formatDate);
    }

	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Generado  ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLTitulo = new javax.swing.JLabel();
        jLCampo = new javax.swing.JLabel();
        jLCultivo = new javax.swing.JLabel();
        jLContrato = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLFechaInicio = new javax.swing.JLabel();
        jLFechaFin = new javax.swing.JLabel();
        jCBCampo = new javax.swing.JComboBox();
        jCBCultivo = new javax.swing.JComboBox();
        jCBContrato = new javax.swing.JComboBox();
        jTFDescripcion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dCCFechaIni = new datechooser.beans.DateChooserCombo();
        dCCFechaIni.setDateFormat(DateUtil.formatDate);
        dCCFechaFin = new datechooser.beans.DateChooserCombo();
        dCCFechaIni.setDateFormat(DateUtil.formatDate);
        jLTitulo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLTitulo.setText("ALTA SECTOR");

        jLCampo.setText("Campo");

        jLCultivo.setText("Cultivo");

        jLContrato.setText("Contrato");

        jLDescripcion.setText("Descripci\u00f3n");

        jLFechaInicio.setText("Feha inicio");

        jLFechaFin.setText("Fecha fin");

        jCBCampo.setModel(new javax.swing.DefaultComboBoxModel(campoDao.getCampos().toArray()));

        jCBCultivo.setModel(new javax.swing.DefaultComboBoxModel(tipoCultivoDao.getTiposCultivo().toArray()));

        jCBContrato.setModel(new javax.swing.DefaultComboBoxModel(contratoDao.getContratos().toArray()));

        jButton1.setText("Aceptar");
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(55, 55, 55)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLCampo)
                            .add(jLCultivo)
                            .add(jLContrato)
                            .add(jLDescripcion)
                            .add(jLFechaInicio)
                            .add(jLFechaFin))
                        .add(22, 22, 22))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(69, Short.MAX_VALUE)
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLTitulo)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(84, 84, 84)
                                .add(jButton2))
                            .add(dCCFechaFin, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .add(dCCFechaIni, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .add(jTFDescripcion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .add(jCBContrato, 0, 176, Short.MAX_VALUE)
                            .add(jCBCultivo, 0, 176, Short.MAX_VALUE)
                            .add(jCBCampo, 0, 176, Short.MAX_VALUE))))
                .add(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jLTitulo)
                .add(38, 38, 38)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLCampo)
                    .add(jCBCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLCultivo)
                    .add(jCBCultivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLContrato)
                    .add(jCBContrato, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLDescripcion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTFDescripcion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLFechaInicio)
                    .add(dCCFechaIni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(18, 18, 18)
                       )
                    .add(layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jLFechaFin))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(dCCFechaFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Dimension dim = new Dimension();
        dim.setSize(500,400);
        this.setPreferredSize(dim);
        this.setAlignmentX(Component.CENTER_ALIGNMENT);
        this.setAlignmentY(Component.CENTER_ALIGNMENT);
    }// </editor-fold>//GEN-END:initComponents

    //CANCELAR
    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
    	this.setVisible(false);
    	this.setEnabled(false);
    }//GEN-LAST:event_jButton2KeyPressed
    //CANCELAR
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    	this.setVisible(false);
    	this.setEnabled(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
    	this.jButton1MouseClicked(null);
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    	Sector sector = new Sector();
    	sector.setDescripcion(this.jTFDescripcion.getText());
    	
    	Campo campo = (Campo) this.jCBCampo.getSelectedItem();
    	sector.setIdcampo(campo.getId());
    	Contrato contrato = (Contrato) this.jCBContrato.getSelectedItem();
    	sector.setIdcontrato(contrato.getId());
    	TipoCultivo tipoCultivo = (TipoCultivo)this.jCBCultivo.getSelectedItem();
    	sector.setIdTipoCultivo(tipoCultivo.getId());
    	try {
    		Date fechaHoraInicio = DateUtil.formatDate.parse(this.dCCFechaIni.getText());
			sector.setFechahorainicio(new Time(fechaHoraInicio.getTime()));
			Date fechaHoraFin = DateUtil.formatDate.parse(this.dCCFechaFin.getText());
			sector.setFechahorafin(new Time(fechaHoraFin.getTime()));
    	} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	
    	sectorDao.insertSector(sector);
    	this.setVisible(false);
    	this.setEnabled(false);
    }//GEN-LAST:event_jButton1MouseClicked
    
    
    // Declaración de varibales -no modificar//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dCCFechaFin;
    private datechooser.beans.DateChooserCombo dCCFechaIni;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBCampo;
    private javax.swing.JComboBox jCBContrato;
    private javax.swing.JComboBox jCBCultivo;
    private javax.swing.JLabel jLCampo;
    private javax.swing.JLabel jLContrato;
    private javax.swing.JLabel jLCultivo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLFechaFin;
    private javax.swing.JLabel jLFechaInicio;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFDescripcion;
    // Fin de declaración de variables//GEN-END:variables
    
}
