/*
 * JPanelConsultarFactura.java
 *
 * Created on 18 de noviembre de 2007, 18:46
 */

package layout.panels;

import java.util.Vector;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import layout.utils.DateUtil;
import scr.dao.FacturacionDao;
import scr.dao.ProductorDao;
import scr.entidades.CabeceraFactura;
import scr.entidades.Productor;
import scr.entidades.RenglonFactura;
import scr.entidades.Rol;
import scr.entidades.Session;


/**
 *
 * @author  Administrador
 */
public class JPanelConsultarFactura extends javax.swing.JPanel {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** Creates new form JPanelConsultarFactura */
    
     public JPanelConsultarFactura() {
        initComponents();
        extraInitComponents();
    }
    
    private void extraInitComponents() {
        loadCombos();
        initLabelsError();
    }
    
    private void initLabelsError() {
        jLabelErrorProductor.setVisible(false);
        jLabelErrorProductor.setVisible(false);
    }
    
    private boolean validateProductor() {
        boolean validate = validateCombo(jComboBoxProductor);
        if(!validate) {
            putError(jLabelErrorProductor, "Debe seleccionar un Productor");
        } else {
            jLabelErrorProductor.setVisible(false);
        }
        return validate;
    }
    
    private void putError(JLabel labelError, String messageError) {
        labelError.setText(messageError);
        labelError.setVisible(true);
    }
    
    private boolean validateCombo(JComboBox jComboBox) {
        int indexSelected = jComboBox.getSelectedIndex();
        return indexSelected >= 0;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProductor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonConsultar = new javax.swing.JButton();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo1.setDateFormat(DateUtil.formatDate);
        jLabelErrorProductor = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Consultas de Facturas");

        jLabel2.setText("Productor");

        jComboBoxProductor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Fecha");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null,null},
                {null, null, null,null},
                {null, null, null,null},
                {null, null, null,null}
            },
            new String [] {"Renglon", "Contrato", "Descripcion", "Monto"
           }
            
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonConsultar.setText("Consultar");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jLabelErrorProductor.setForeground(new java.awt.Color(255, 0, 51));
        jLabelErrorProductor.setText("jLabel4");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(jLabel3))
                                .add(83, 83, 83)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(dateChooserCombo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(jComboBoxProductor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(43, 43, 43)
                                        .add(jLabelErrorProductor))))))
                    .add(layout.createSequentialGroup()
                        .add(79, 79, 79)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(167, 167, 167)
                        .add(jButtonConsultar)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(jLabel1)
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jComboBoxProductor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelErrorProductor))
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(dateChooserCombo1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(13, 13, 13)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButtonConsultar)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        boolean validateOk = validateProductor();
        if(validateOk) {
        	String fecha = this.dateChooserCombo1.getText();
        	Productor productor = (Productor)this.jComboBoxProductor.getSelectedItem();
        	FacturacionDao dao = new FacturacionDao();
        	CabeceraFactura cabecera = dao.getCabeceraFactura(fecha,productor.getIdProductor());
        	if(cabecera == null) {
        		JOptionPane.showMessageDialog(new JFrame(), "El productor seleccionado\nno posee facturas para la fecha seleccionada", "Dialog",
    	    	        JOptionPane.ERROR_MESSAGE);
        	} else {
        		Vector renglones = dao.getRenglonesFactura(cabecera.getIdCabecera());
            	loadTabla(renglones);
            	jLabelErrorProductor.setText("TOTAL: $ " + cabecera.getMontototal());
            	jLabelErrorProductor.setVisible(true);
        	}
        	
        } 
    }//GEN-LAST:event_jButtonConsultarActionPerformed
    
    private void loadTabla(Vector renglones){
    	String cabecera[] = new String [] {"Renglon", "Contrato", "Descripcion", "Monto"};
    	Object [][] tabla = new Object[renglones.size()][cabecera.length];
    	 
    	for (int i = 0; i < renglones.size(); i++)
    	{
    		tabla[i][0] = new Integer(i);
    		tabla[i][1] = ((RenglonFactura)renglones.get(i)).getIdContrato();
    		tabla[i][2] = ((RenglonFactura)renglones.get(i)).getDescripcion();
    		tabla[i][3] = ((RenglonFactura)renglones.get(i)).getMonto();
    	}
    	
        jTable1.setModel(new javax.swing.table.DefaultTableModel(tabla, cabecera ));
        jScrollPane1.setViewportView(jTable1);
    	
    }
    
    private void loadCombos() {
        loadComboProductor();
    }
    
    private void loadComboProductor() {
    	//int idRol = Session.getInstance().getUsuario().getIdRol();
    	int idRol=1;
        ProductorDao dao = new ProductorDao();
        if(Rol.PRODUCTOR.getIdRol() == idRol) {
        	Productor prod = dao.getProductorDeUnUsuario(Session.getInstance().getUsuario().getId());
        	jComboBoxProductor.addItem(prod);
        } else if(Rol.ADMINISTRADOR.getIdRol() == idRol) {
        	jComboBoxProductor.setModel(new javax.swing.DefaultComboBoxModel(dao.getProductores().toArray()));        	
            System.out.println("ADMINISTRADOR");
        }
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JComboBox jComboBoxProductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelErrorProductor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
